spring:
  application:
    name: Student Portal


  #JPA
  jpa:
    show-sql: true

  #Spring Datasource Connection Pooling configuration
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/student_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      validation-query: SELECT 1
      max-active: 5
      max-idle: 3
      max-wait: 8000
    hikari:
      schema: student_db# Set the default schema here

  #Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:mysql://localhost:3306?useSSL=false
    schemas: student_db
    user: root
    password: root